# List with common red flags in emails or messages that may indicate spam or scams.
RED_FLAGS = [
    "lottery win",
    "bitcoin invest",
    "make money fast",
    "get rich quick",
    "wire transfer",
    "nigerian prince",
    "bank account details",
    "credit card information",
    "limited time offer",
    "enlarge your",
    "casino bonus",
    "online pharmacy",
    "singles in your area",
    "meet local singles",
    "cash prize",
    "you've won",
    "earn money from home",
    "investment opportunity",
    "special offer",
    "discount coupon",
    "act now",
    "free money",
    "100% free",
    "amazing opportunity",
    "instant approval",
    "Business opportunity for you",
    "Confidential proposal",
    "Investment partnership request",
    "From the desk of the director",
    "Government contract offer",
    "Urgent business proposal",
    "Exclusive business opportunity",
    "You have won $[amount]",
    "Congratulations, you are the winner",
    "Funds ready for transfer",
    "Claim your prize now",
    "Contact us immediately to receive funds",
    "Urgent response needed",
    "Your inheritance is waiting",
    "Bank transfer confirmation needed"
]
